// 가이드 본문 구성(순서대로 렌더). 문구 키 = gd.<키> (i18n/parts/guide.<lang>.json), 그림 = guide/<이름>.png.
// group = 큰 묶음(목차에 나옴) · sec = 절 · intro/p = 문단 · ul = 목록 · note = 참고 상자
// fig = 그림 목록(2개면 나란히), kind: 'crop' = 부분 그림(촬영 크기의 절반).
// 그림 촬영: tools/redesign/guide_shots_v2.js — 여기 fig 이름과 1:1.
export const GUIDE = [
  { intro: 'intro' },
  { fig: ['overview'] },

  { group: 'team' },
  { p: 'team.p1' },
  { fig: ['team'] },
  { ul: ['team.li1', 'team.li2', 'team.li3', 'team.li4', 'team.li5'] },
  { sec: 'grow' },
  { p: 'grow.p1' },
  { fig: ['grow'] },
  { p: 'grow.p2' },
  { fig: ['grow-spec'], kind: 'crop' },
  { ul: ['grow.li1', 'grow.li2', 'grow.li3', 'grow.li4', 'grow.li5'] },
  { fig: ['grow-skills'], kind: 'crop' },
  { p: 'grow.p3' },
  { note: 'grow.note1' },
  { fig: ['team-chips'], kind: 'crop' },
  { p: 'grow.p4' },

  { group: 'plan' },
  { p: 'plan.p1' },
  { fig: ['plan'] },
  { sec: 'order' },
  { p: 'order.p1' },
  { ul: ['order.li1', 'order.li2'] },
  { fig: ['plan-direct'], kind: 'crop' },
  { p: 'order.p2' },
  { sec: 'cell' },
  { p: 'cell.p1' },
  { fig: ['plan-cell'], kind: 'crop' },
  { ul: ['cell.li1', 'cell.li2', 'cell.li3'] },
  { sec: 'preset' },
  { p: 'preset.p1' },
  { ul: ['preset.li0', 'preset.li1', 'preset.li2', 'preset.li3', 'preset.li4', 'preset.li5', 'preset.li6'] },
  { note: 'preset.note1' },
  { sec: 'ally' },
  { p: 'ally.p1' },
  { p: 'ally.p2' },
  { sec: 'imm' },
  { p: 'imm.p1' },
  { ul: ['imm.li1', 'imm.li2', 'imm.li3'] },
  { sec: 'exc' },
  { p: 'exc.p1' },
  { fig: ['plan-exc'], kind: 'crop' },
  { sec: 'preview' },
  { p: 'preview.p1' },
  { fig: ['plan-preview'], kind: 'crop' },
  { p: 'preview.p2' },
  { ul: ['preview.li1', 'preview.li2', 'preview.li3', 'preview.li4'] },

  { group: 'adv' },
  { p: 'adv.p1' },
  { fig: ['adv-switch'], kind: 'crop' },
  { p: 'adv.p2' },
  { ul: ['adv.li1', 'adv.li2', 'adv.li3'] },
  { note: 'adv.note1' },
  { sec: 'mode' },
  { p: 'mode.p1' },
  { ul: ['mode.li1', 'mode.li2', 'mode.li3'] },
  { fig: ['adv-step1'], kind: 'crop' },
  { p: 'mode.p2' },
  { sec: 'assist' },
  { p: 'assist.p1' },
  { fig: ['adv-proc'], kind: 'crop' },
  { ul: ['assist.li1', 'assist.li2', 'assist.li3'] },
  { note: 'assist.note1' },
  { sec: 'exc2' },
  { p: 'exc2.p1' },
  { sec: 'sync' },
  { p: 'sync.p1' },
  { ul: ['sync.li1', 'sync.li2', 'sync.li3', 'sync.li4'] },
  { fig: ['adv-sync'], kind: 'crop' },
  { p: 'sync.p2' },
  { note: 'sync.note1' },
  { sec: 'grid' },
  { p: 'grid.p1' },
  { fig: ['adv-grid'] },
  { ul: ['grid.li1', 'grid.li2', 'grid.li3', 'grid.li4'] },
  { fig: ['adv-cell', 'adv-row'], kind: 'crop' },
  { sec: 'turn' },
  { p: 'turn.p1' },
  { fig: ['turn-edit'], kind: 'crop' },
  { ul: ['turn.li1', 'turn.li2', 'turn.li3'] },
  { sec: 'prio' },
  { p: 'prio.p1' },
  { ul: ['prio.li1', 'prio.li2', 'prio.li3', 'prio.li4', 'prio.li5'] },
  { p: 'prio.p2' },

  { group: 'cond' },
  { p: 'cond.p1' },
  { fig: ['cond'], kind: 'crop' },
  { ul: ['cond.li1', 'cond.li2', 'cond.li3', 'cond.li4', 'cond.li5', 'cond.li6', 'cond.li7'] },
  { sec: 'tdmg' },
  { p: 'tdmg.p1' },
  { ul: ['tdmg.li1', 'tdmg.li2', 'tdmg.li3'] },
  { fig: ['tdmg'], kind: 'crop' },
  { sec: 'altar' },
  { p: 'altar.p1' },
  { ul: ['altar.li1', 'altar.li2', 'altar.li3', 'altar.li4', 'altar.li5'] },
  { fig: ['altar'], kind: 'crop' },
  { note: 'altar.note1' },
  { sec: 'run' },
  { p: 'run.p1' },

  { group: 'result' },
  { p: 'result.p1' },
  { sec: 'hero' },
  { fig: ['result-hero'], kind: 'crop' },
  { p: 'hero.p1' },
  { sec: 'turns' },
  { p: 'turns.p1' },
  { fig: ['result-turns'], kind: 'crop' },
  { sec: 'contrib' },
  { p: 'contrib.p1' },
  { fig: ['result-contrib'], kind: 'crop' },
  { sec: 'log' },
  { p: 'log.p1' },
  { fig: ['result-log'] },
  { ul: ['log.li1', 'log.li2', 'log.li3', 'log.li4'] },
  { fig: ['result-calc'], kind: 'crop' },
  { note: 'log.note1' },

  { group: 'records' },
  { p: 'records.p1' },
  { ul: ['records.li1', 'records.li2', 'records.li3', 'records.li4'] },
  { fig: ['records', 'export'] },
  { note: 'records.note1' },

  { group: 'compare' },
  { p: 'compare.p1' },
  { ul: ['compare.li1', 'compare.li2', 'compare.li3', 'compare.li4', 'compare.li5'] },
  { fig: ['compare'] },

  { group: 'nav' },
  { p: 'nav.p1' },
  { fig: ['topbar'] },
  { ul: ['nav.li1', 'nav.li2', 'nav.li3', 'nav.li4'] },
  { sec: 'menu' },
  { p: 'menu.p1' },
  { fig: ['menu'], kind: 'crop' },
  { ul: ['menu.li1', 'menu.li2', 'menu.li3', 'menu.li4', 'menu.li5'] },
  { p: 'menu.p2' },
  { sec: 'lounge' },
  { p: 'lounge.p1' },
  { ul: ['lounge.li1', 'lounge.li2', 'lounge.li3'] },

  { note: 'end.note1' },
];
